model = "gpt-5.4"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
model_context_window = 1000000
model_auto_compact_token_limit = 600000
model_verbosity = "high"
file_opener = "none"
sandbox_mode = "danger-full-access"
approval_policy = "never"
personality = "pragmatic"
web_search = "live"
service_tier = "fast"
model_instructions_file = "~/.codex/instructions.md"

notify = ["/Users/tammersaleh/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = true

[marketplaces.openai-bundled]
last_updated = "2026-07-06T22:30:28Z"
source_type = "local"
source = "/Users/tammersaleh/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-06T22:30:44Z"
source_type = "local"
source = "/Users/tammersaleh/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."sites@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[desktop]
conversationDetailMode = "STEPS_PROSE"
sansFontSize = 14
codeFontSize = 13
ambient-suggestions-enabled = false

[features]
js_repl = false
hooks = false

[mcp_servers.node_repl]
args = []
command = "/private/var/folders/4b/2c4j5q_d00vfrr6r41tbmwfc0000gn/T/AppTranslocation/9FF88AEA-F85E-431D-B265-0B224E4A8EF9/d/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/private/var/folders/4b/2c4j5q_d00vfrr6r41tbmwfc0000gn/T/AppTranslocation/9FF88AEA-F85E-431D-B265-0B224E4A8EF9/d/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/private/var/folders/4b/2c4j5q_d00vfrr6r41tbmwfc0000gn/T/AppTranslocation/9FF88AEA-F85E-431D-B265-0B224E4A8EF9/d/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/tammersaleh/.codex"
CODEX_HOME = "/Users/tammersaleh/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "60e4902788f207f88fd09344dfeafe07769488bdb2924bbb12b322c3b9d2b999"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.101652"
CODEX_CLI_PATH = "/private/var/folders/4b/2c4j5q_d00vfrr6r41tbmwfc0000gn/T/AppTranslocation/9FF88AEA-F85E-431D-B265-0B224E4A8EF9/d/Codex.app/Contents/Resources/codex"
