local h = require('helpers')

describe("ftplugin/markdown", function()
  before_each(function()
    h.reset()
    vim.bo.filetype = 'markdown'
  end)

  describe("options", function()
    it("sets shiftwidth to 4", function()
      assert.equals(4, vim.bo.shiftwidth)
    end)

    it("sets tabstop to 4", function()
      assert.equals(4, vim.bo.tabstop)
    end)

    it("disables conceal", function()
      assert.equals(0, vim.wo.conceallevel)
    end)

    it("enables line break", function()
      assert.is_true(vim.wo.linebreak)
    end)

    it("enables folding", function()
      assert.is_true(vim.wo.foldenable)
    end)

    it("enables spell check", function()
      assert.is_true(vim.wo.spell)
    end)

    it("uses expression folding", function()
      assert.equals('expr', vim.wo.foldmethod)
    end)
  end)

  describe("visual mode bullet formatting", function()
    it("adds dash bullets with -", function()
      h.set_buf({ "item one", "item two", "item three" })
      h.set_cursor(1)
      h.feed("Vj-")
      assert.are.same({ "- item one", "- item two", "item three" }, h.get_buf())
    end)

    it("adds asterisk bullets with *", function()
      h.set_buf({ "item one", "item two", "item three" })
      h.set_cursor(1)
      h.feed("Vj*")
      assert.are.same({ "* item one", "* item two", "item three" }, h.get_buf())
    end)

    it("adds numbered list with #", function()
      h.set_buf({ "item one", "item two", "item three" })
      h.set_cursor(1)
      h.feed("Vj#")
      assert.are.same({ "1. item one", "1. item two", "item three" }, h.get_buf())
    end)
  end)

  describe("bullet cycling", function()
    describe("normal mode", function()
      it("Tab on a paragraph turns it into a bullet", function()
        h.set_buf({ "some text", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "- some text", "other" }, h.get_buf())
      end)

      it("Tab on an empty line creates a bullet", function()
        h.set_buf({ "", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "- ", "other" }, h.get_buf())
      end)

      it("matches asterisk bullet style from above", function()
        h.set_buf({ "* item one", "some text", "other" })
        h.set_cursor(2)
        h.feed("<Tab>")
        assert.are.same({ "* item one", "* some text", "other" }, h.get_buf())
      end)

      it("matches plus bullet style from below", function()
        h.set_buf({ "some text", "+ item one", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "+ some text", "+ item one", "other" }, h.get_buf())
      end)

      it("prefers nearest bullet above over below", function()
        h.set_buf({ "* above", "some text", "- below" })
        h.set_cursor(2)
        h.feed("<Tab>")
        assert.are.same({ "* above", "* some text", "- below" }, h.get_buf())
      end)

      it("matches bullet style across blank lines", function()
        h.set_buf({ "* item one", "", "some text" })
        h.set_cursor(3)
        h.feed("<Tab>")
        assert.are.same({ "* item one", "", "* some text" }, h.get_buf())
      end)

      it("continues ordered list numbering", function()
        h.set_buf({ "1. first", "2. second", "next item" })
        h.set_cursor(3)
        h.feed("<Tab>")
        assert.are.same({ "1. first", "2. second", "3. next item" }, h.get_buf())
      end)

      it("falls back to most common style in document", function()
        h.set_buf({ "* top", "* list", "", "# Heading", "", "some text" })
        h.set_cursor(6)
        h.feed("<Tab>")
        assert.are.same({ "* top", "* list", "", "# Heading", "", "* some text" }, h.get_buf())
      end)

      it("continues ordered list from above a list", function()
        h.set_buf({ "some text", "1. first", "2. second" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "1. some text", "1. first", "2. second" }, h.get_buf())
      end)

      it("continues ordered list across blank line", function()
        h.set_buf({ "1. first", "2. second", "", "next item" })
        h.set_cursor(4)
        h.feed("<Tab>")
        assert.are.same({ "1. first", "2. second", "", "3. next item" }, h.get_buf())
      end)

      it("defaults to dash when no bullets exist", function()
        h.set_buf({ "just prose", "some text" })
        h.set_cursor(2)
        h.feed("<Tab>")
        assert.are.same({ "just prose", "- some text" }, h.get_buf())
      end)

      it("Tab on a bullet indents it", function()
        h.set_buf({ "- item", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "    - item", "other" }, h.get_buf())
      end)

      it("S-Tab on an indented bullet dedents it", function()
        h.set_buf({ "    - item", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "- item", "other" }, h.get_buf())
      end)

      it("S-Tab on a top-level bullet removes it", function()
        h.set_buf({ "- some text", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("S-Tab on an empty top-level bullet removes it", function()
        h.set_buf({ "- ", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "", "other" }, h.get_buf())
      end)

      it("S-Tab on a plain paragraph is a no-op", function()
        h.set_buf({ "some text", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("Tab on indented text indents further", function()
        h.set_buf({ "    some text", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "        some text", "other" }, h.get_buf())
      end)

      it("S-Tab on indented text dedents", function()
        h.set_buf({ "    some text", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("Tab on H1 deepens to H2", function()
        h.set_buf({ "# Heading", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "## Heading", "other" }, h.get_buf())
      end)

      it("Tab on H2 deepens to H3", function()
        h.set_buf({ "## Heading", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "### Heading", "other" }, h.get_buf())
      end)

      it("Tab on H6 is a no-op", function()
        h.set_buf({ "###### Heading", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "###### Heading", "other" }, h.get_buf())
      end)

      it("S-Tab on H1 is a no-op", function()
        h.set_buf({ "# Heading", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "# Heading", "other" }, h.get_buf())
      end)

      it("S-Tab on H2 reduces to H1", function()
        h.set_buf({ "## Heading", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "# Heading", "other" }, h.get_buf())
      end)

      it("S-Tab on H6 reduces to H5", function()
        h.set_buf({ "###### Heading", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "##### Heading", "other" }, h.get_buf())
      end)
    end)

    describe("visual mode", function()
      it("Tab on plain lines turns them all into bullets", function()
        h.set_buf({ "asdf", "asdf" })
        h.set_cursor(1)
        h.feed("Vj<Tab>")
        assert.are.same({ "- asdf", "- asdf" }, h.get_buf())
      end)

      it("Tab matches bullet style from above the selection", function()
        h.set_buf({ "* item one", "asdf", "asdf" })
        h.set_cursor(2)
        h.feed("Vj<Tab>")
        assert.are.same({ "* item one", "* asdf", "* asdf" }, h.get_buf())
      end)

      it("Tab continues ordered list numbering", function()
        h.set_buf({ "1. first", "asdf", "asdf" })
        h.set_cursor(2)
        h.feed("Vj<Tab>")
        assert.are.same({ "1. first", "2. asdf", "3. asdf" }, h.get_buf())
      end)

      it("Tab on bullets indents them all", function()
        h.set_buf({ "- one", "- two" })
        h.set_cursor(1)
        h.feed("Vj<Tab>")
        assert.are.same({ "    - one", "    - two" }, h.get_buf())
      end)

      it("Tab applies per-line on a mixed selection", function()
        h.set_buf({ "asdf", "- foo", "asdf" })
        h.set_cursor(1)
        h.feed("Vjj<Tab>")
        assert.are.same({ "- asdf", "    - foo", "- asdf" }, h.get_buf())
      end)

      it("S-Tab on top-level bullets removes them", function()
        h.set_buf({ "- one", "- two" })
        h.set_cursor(1)
        h.feed("Vj<S-Tab>")
        assert.are.same({ "one", "two" }, h.get_buf())
      end)

      it("S-Tab on indented bullets dedents them", function()
        h.set_buf({ "    - one", "    - two" })
        h.set_cursor(1)
        h.feed("Vj<S-Tab>")
        assert.are.same({ "- one", "- two" }, h.get_buf())
      end)

      it("keeps selection active after Tab", function()
        h.set_buf({ "asdf", "asdf" })
        h.set_cursor(1)
        h.feed("Vj<Tab>")
        assert.equals("V", h.get_mode())
        h.ensure_normal()
      end)

      it("keeps selection active after S-Tab", function()
        h.set_buf({ "- one", "- two" })
        h.set_cursor(1)
        h.feed("Vj<S-Tab>")
        assert.equals("V", h.get_mode())
        h.ensure_normal()
      end)

      it("Tab deepens all selected headings", function()
        h.set_buf({ "# One", "# Two" })
        h.set_cursor(1)
        h.feed("Vj<Tab>")
        assert.are.same({ "## One", "## Two" }, h.get_buf())
      end)

      it("S-Tab reduces all selected headings", function()
        h.set_buf({ "## One", "## Two" })
        h.set_cursor(1)
        h.feed("Vj")
        h.feed("<S-Tab>")
        assert.are.same({ "# One", "# Two" }, h.get_buf())
      end)

      it("Tab on a mixed selection only deepens headings", function()
        h.set_buf({ "# Heading", "- bullet", "asdf" })
        h.set_cursor(1)
        h.feed("Vjj")
        h.feed("<Tab>")
        assert.are.same({ "## Heading", "- bullet", "asdf" }, h.get_buf())
      end)

      it("S-Tab on a mixed selection only reduces headings", function()
        h.set_buf({ "## Heading", "- bullet", "asdf" })
        h.set_cursor(1)
        h.feed("Vjj")
        h.feed("<S-Tab>")
        assert.are.same({ "# Heading", "- bullet", "asdf" }, h.get_buf())
      end)

      it("Tab is a no-op if any selected heading is at H6", function()
        h.set_buf({ "##### Five", "###### Six" })
        h.set_cursor(1)
        h.feed("Vj")
        h.feed("<Tab>")
        assert.are.same({ "##### Five", "###### Six" }, h.get_buf())
      end)

      it("S-Tab is a no-op if any selected heading is at H1", function()
        h.set_buf({ "# One", "## Two" })
        h.set_cursor(1)
        h.feed("Vj")
        h.feed("<S-Tab>")
        assert.are.same({ "# One", "## Two" }, h.get_buf())
      end)
    end)

    describe("insert mode", function()
      it("Tab on a paragraph turns it into a bullet", function()
        h.set_buf({ "some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<Tab>")
        h.ensure_normal()
        assert.are.same({ "- some text", "other" }, h.get_buf())
      end)

      it("Tab on an empty line creates a bullet", function()
        h.set_buf({ "", "other" })
        h.set_cursor(1, 0)
        h.feed("i<Tab>")
        h.ensure_normal()
        assert.are.same({ "- ", "other" }, h.get_buf())
      end)

      it("Tab on an empty line moves cursor past the bullet prefix", function()
        h.set_buf({ "", "other" })
        h.set_cursor(1, 0)
        h.feed("i<Tab>")
        -- After <Esc>, cursor is one column left of where it was in insert mode.
        -- We want insert-mode cursor at col 2 (end of "- "), which becomes col 1 after Esc.
        h.ensure_normal()
        local pos = h.get_cursor()
        assert.equals(1, pos[2], "expected cursor at col 1 after Esc (col 2 in insert mode)")
      end)

      it("Tab in the middle of text keeps relative cursor position", function()
        h.set_buf({ "hello", "other" })
        h.set_cursor(1, 2)  -- between 'he' and 'llo'
        h.feed("i<Tab>")
        h.ensure_normal()
        assert.are.same({ "- hello", "other" }, h.get_buf())
        -- Insert-mode cursor was at col 2 (between 'he' and 'llo' in "hello").
        -- After tab adds "- " prefix, cursor should still be between 'he' and 'llo'
        -- which is now col 4 in "- hello". After Esc, col 3.
        local pos = h.get_cursor()
        assert.equals(3, pos[2], "expected cursor to maintain relative position after prefix added")
      end)

      it("Tab on a bullet line keeps relative cursor position after indent", function()
        h.set_buf({ "- item", "other" })
        h.set_cursor(1, 3)  -- on 'i' of 'item'
        h.feed("i<Tab>")
        h.ensure_normal()
        assert.are.same({ "    - item", "other" }, h.get_buf())
        -- Cursor was on 'i' at col 3. After 4 spaces added, 'i' is at col 7.
        -- After Esc from insert mode at col 7, cursor at col 6.
        local pos = h.get_cursor()
        assert.equals(6, pos[2], "expected cursor to follow the 'i' character")
      end)

      it("S-Tab on indented bullet keeps relative cursor position", function()
        h.set_buf({ "    - item", "other" })
        h.set_cursor(1, 7)  -- on 'i' of 'item'
        h.feed("i<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "- item", "other" }, h.get_buf())
        -- 'i' moved from col 7 to col 3. After Esc, col 2.
        local pos = h.get_cursor()
        assert.equals(2, pos[2], "expected cursor to follow the 'i' character")
      end)

      it("Tab on a bullet indents it", function()
        h.set_buf({ "- item", "other" })
        h.set_cursor(1, 5)
        h.feed("a<Tab>")
        h.ensure_normal()
        assert.are.same({ "    - item", "other" }, h.get_buf())
      end)

      it("S-Tab on a top-level bullet removes it", function()
        h.set_buf({ "- some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("S-Tab on an indented bullet dedents it", function()
        h.set_buf({ "    - item", "other" })
        h.set_cursor(1, 5)
        h.feed("a<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "- item", "other" }, h.get_buf())
      end)

      it("S-Tab on a plain paragraph is a no-op", function()
        h.set_buf({ "some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("Tab on indented text indents further", function()
        h.set_buf({ "    some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<Tab>")
        h.ensure_normal()
        assert.are.same({ "        some text", "other" }, h.get_buf())
      end)

      it("S-Tab on indented text dedents", function()
        h.set_buf({ "    some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)
    end)
  end)

  describe("fold expression", function()
    it("folds on ATX-style headers", function()
      h.set_buf({ "# Heading 1", "content", "## Heading 2", "more content" })
      -- The fold expression is set, verify foldmethod
      assert.equals('expr', vim.wo.foldmethod)
      -- Verify the fold level of line 1 (# = level 1)
      vim.cmd('normal! zx') -- recompute folds
      assert.equals(1, vim.fn.foldlevel(1))
    end)

    it("assigns deeper fold levels to deeper headers", function()
      h.set_buf({ "# H1", "text", "## H2", "text", "### H3", "text" })
      vim.cmd('normal! zx')
      assert.equals(1, vim.fn.foldlevel(1))
      assert.equals(2, vim.fn.foldlevel(3))
      assert.equals(3, vim.fn.foldlevel(5))
    end)
  end)
end)
