local h = require('helpers')

describe("ftplugin/markdown", function()
  before_each(function()
    h.reset()
    vim.bo.filetype = 'markdown'
  end)

  describe("options", function()
    it("sets shiftwidth to 4", function()
      assert.equals(4, vim.bo.shiftwidth)
    end)

    it("sets tabstop to 4", function()
      assert.equals(4, vim.bo.tabstop)
    end)

    it("disables conceal", function()
      assert.equals(0, vim.wo.conceallevel)
    end)

    it("enables line break", function()
      assert.is_true(vim.wo.linebreak)
    end)

    it("enables folding", function()
      assert.is_true(vim.wo.foldenable)
    end)

    it("enables spell check", function()
      assert.is_true(vim.wo.spell)
    end)

    it("uses expression folding", function()
      assert.equals('expr', vim.wo.foldmethod)
    end)
  end)

  describe("visual mode bullet formatting", function()
    it("adds dash bullets with -", function()
      h.set_buf({ "item one", "item two", "item three" })
      h.set_cursor(1)
      h.feed("Vj-")
      assert.are.same({ "- item one", "- item two", "item three" }, h.get_buf())
    end)

    it("adds asterisk bullets with *", function()
      h.set_buf({ "item one", "item two", "item three" })
      h.set_cursor(1)
      h.feed("Vj*")
      assert.are.same({ "* item one", "* item two", "item three" }, h.get_buf())
    end)

    it("adds numbered list with #", function()
      h.set_buf({ "item one", "item two", "item three" })
      h.set_cursor(1)
      h.feed("Vj#")
      assert.are.same({ "1. item one", "1. item two", "item three" }, h.get_buf())
    end)
  end)

  describe("bullet cycling", function()
    describe("normal mode", function()
      it("Tab on a paragraph turns it into a bullet", function()
        h.set_buf({ "some text", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "- some text", "other" }, h.get_buf())
      end)

      it("Tab on an empty line creates a bullet", function()
        h.set_buf({ "", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "- ", "other" }, h.get_buf())
      end)

      it("matches asterisk bullet style from above", function()
        h.set_buf({ "* item one", "some text", "other" })
        h.set_cursor(2)
        h.feed("<Tab>")
        assert.are.same({ "* item one", "* some text", "other" }, h.get_buf())
      end)

      it("matches plus bullet style from below", function()
        h.set_buf({ "some text", "+ item one", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "+ some text", "+ item one", "other" }, h.get_buf())
      end)

      it("prefers nearest bullet above over below", function()
        h.set_buf({ "* above", "some text", "- below" })
        h.set_cursor(2)
        h.feed("<Tab>")
        assert.are.same({ "* above", "* some text", "- below" }, h.get_buf())
      end)

      it("matches bullet style across blank lines", function()
        h.set_buf({ "* item one", "", "some text" })
        h.set_cursor(3)
        h.feed("<Tab>")
        assert.are.same({ "* item one", "", "* some text" }, h.get_buf())
      end)

      it("continues ordered list numbering", function()
        h.set_buf({ "1. first", "2. second", "next item" })
        h.set_cursor(3)
        h.feed("<Tab>")
        assert.are.same({ "1. first", "2. second", "3. next item" }, h.get_buf())
      end)

      it("falls back to most common style in document", function()
        h.set_buf({ "* top", "* list", "", "# Heading", "", "some text" })
        h.set_cursor(6)
        h.feed("<Tab>")
        assert.are.same({ "* top", "* list", "", "# Heading", "", "* some text" }, h.get_buf())
      end)

      it("continues ordered list from above a list", function()
        h.set_buf({ "some text", "1. first", "2. second" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "1. some text", "1. first", "2. second" }, h.get_buf())
      end)

      it("continues ordered list across blank line", function()
        h.set_buf({ "1. first", "2. second", "", "next item" })
        h.set_cursor(4)
        h.feed("<Tab>")
        assert.are.same({ "1. first", "2. second", "", "3. next item" }, h.get_buf())
      end)

      it("defaults to dash when no bullets exist", function()
        h.set_buf({ "just prose", "some text" })
        h.set_cursor(2)
        h.feed("<Tab>")
        assert.are.same({ "just prose", "- some text" }, h.get_buf())
      end)

      it("Tab on a bullet indents it", function()
        h.set_buf({ "- item", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "    - item", "other" }, h.get_buf())
      end)

      it("S-Tab on an indented bullet dedents it", function()
        h.set_buf({ "    - item", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "- item", "other" }, h.get_buf())
      end)

      it("S-Tab on a top-level bullet removes it", function()
        h.set_buf({ "- some text", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("S-Tab on an empty top-level bullet removes it", function()
        h.set_buf({ "- ", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "", "other" }, h.get_buf())
      end)

      it("S-Tab on a plain paragraph is a no-op", function()
        h.set_buf({ "some text", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("Tab on indented text indents further", function()
        h.set_buf({ "    some text", "other" })
        h.set_cursor(1)
        h.feed("<Tab>")
        assert.are.same({ "        some text", "other" }, h.get_buf())
      end)

      it("S-Tab on indented text dedents", function()
        h.set_buf({ "    some text", "other" })
        h.set_cursor(1)
        h.feed("<S-Tab>")
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)
    end)

    describe("insert mode", function()
      it("Tab on a paragraph turns it into a bullet", function()
        h.set_buf({ "some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<Tab>")
        h.ensure_normal()
        assert.are.same({ "- some text", "other" }, h.get_buf())
      end)

      it("Tab on an empty line creates a bullet", function()
        h.set_buf({ "", "other" })
        h.set_cursor(1, 0)
        h.feed("i<Tab>")
        h.ensure_normal()
        assert.are.same({ "- ", "other" }, h.get_buf())
      end)

      it("Tab on a bullet indents it", function()
        h.set_buf({ "- item", "other" })
        h.set_cursor(1, 5)
        h.feed("a<Tab>")
        h.ensure_normal()
        assert.are.same({ "    - item", "other" }, h.get_buf())
      end)

      it("S-Tab on a top-level bullet removes it", function()
        h.set_buf({ "- some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("S-Tab on an indented bullet dedents it", function()
        h.set_buf({ "    - item", "other" })
        h.set_cursor(1, 5)
        h.feed("a<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "- item", "other" }, h.get_buf())
      end)

      it("S-Tab on a plain paragraph is a no-op", function()
        h.set_buf({ "some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)

      it("Tab on indented text indents further", function()
        h.set_buf({ "    some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<Tab>")
        h.ensure_normal()
        assert.are.same({ "        some text", "other" }, h.get_buf())
      end)

      it("S-Tab on indented text dedents", function()
        h.set_buf({ "    some text", "other" })
        h.set_cursor(1, 5)
        h.feed("a<S-Tab>")
        h.ensure_normal()
        assert.are.same({ "some text", "other" }, h.get_buf())
      end)
    end)
  end)

  describe("fold expression", function()
    it("folds on ATX-style headers", function()
      h.set_buf({ "# Heading 1", "content", "## Heading 2", "more content" })
      -- The fold expression is set, verify foldmethod
      assert.equals('expr', vim.wo.foldmethod)
      -- Verify the fold level of line 1 (# = level 1)
      vim.cmd('normal! zx') -- recompute folds
      assert.equals(1, vim.fn.foldlevel(1))
    end)

    it("assigns deeper fold levels to deeper headers", function()
      h.set_buf({ "# H1", "text", "## H2", "text", "### H3", "text" })
      vim.cmd('normal! zx')
      assert.equals(1, vim.fn.foldlevel(1))
      assert.equals(2, vim.fn.foldlevel(3))
      assert.equals(3, vim.fn.foldlevel(5))
    end)
  end)
end)
