local h = require('helpers')

describe("markdown bullet continuation on <CR> (with plugins)", function()
  before_each(function()
    h.reset()
    vim.bo.filetype = 'markdown'
    vim.bo.shiftwidth = 4
    vim.bo.tabstop = 4
    vim.bo.expandtab = true
  end)

  it("continues the bullet at end of line", function()
    h.set_buf({ "- one" })
    h.set_cursor(1, 4)
    h.feed("a<CR>two")
    h.ensure_normal()
    assert.are.same({ "- one", "- two" }, h.get_buf())
  end)

  it("continues the bullet when splitting mid-line", function()
    h.set_buf({ "- one two" })
    h.set_cursor(1, 5)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- one", "- two" }, h.get_buf())
  end)

  it("leaves the cursor before the moved text", function()
    h.set_buf({ "- one two" })
    h.set_cursor(1, 5)
    h.feed("i<CR>X")
    h.ensure_normal()
    assert.are.same({ "- one", "- Xtwo" }, h.get_buf())
  end)

  it("keeps the indent when splitting a nested bullet", function()
    h.set_buf({ "- parent", "    - one two" })
    h.set_cursor(2, 9)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- parent", "    - one", "    - two" }, h.get_buf())
  end)

  it("numbers the new item when splitting an ordered list", function()
    h.set_buf({ "1. one two", "2. three" })
    h.set_cursor(1, 6)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "1. one", "2. two", "3. three" }, h.get_buf())
  end)

  it("lets bullets.vim renumber a list that is out of order", function()
    h.set_buf({ "5. one two", "8. three" })
    h.set_cursor(1, 6)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "1. one", "2. two", "3. three" }, h.get_buf())
  end)

  it("continues a ) ordered list", function()
    h.set_buf({ "1) one two" })
    h.set_cursor(1, 6)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "1) one", "2) two" }, h.get_buf())
  end)

  it("nests the new item when the split leaves a colon at the end", function()
    h.set_buf({ "- head: tail" })
    h.set_cursor(1, 7)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- head:", "    * tail" }, h.get_buf())
  end)

  it("does not nest when only the moved text ends in a colon", function()
    h.set_buf({ "- head tail:" })
    h.set_cursor(1, 6)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- head", "- tail:" }, h.get_buf())
  end)

  it("splits a checkbox item into an unchecked item", function()
    h.set_buf({ "- [x] one two" })
    h.set_cursor(1, 9)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- [x] one", "- [ ] two" }, h.get_buf())
  end)

  it("splits after a multibyte character", function()
    h.set_buf({ "- café résumé" })
    h.set_cursor(1, 8) -- byte offset: "- café " is 8 bytes
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- café", "- résumé" }, h.get_buf())
  end)

  it("treats a split inside the marker padding as a plain newline", function()
    h.set_buf({ "-  one" })
    h.set_cursor(1, 2)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- ", "one" }, h.get_buf())
  end)

  it("treats a split before checkbox text as a plain newline", function()
    h.set_buf({ "- [x] one" })
    h.set_cursor(1, 6)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- [x] ", "one" }, h.get_buf())
  end)

  it("splits a plain paragraph without adding a bullet", function()
    h.set_buf({ "one two" })
    h.set_cursor(1, 3)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "one", "two" }, h.get_buf())
  end)

  it("splits before the item text without adding a bullet", function()
    h.set_buf({ "- one" })
    h.set_cursor(1, 2)
    h.feed("i<CR>")
    h.ensure_normal()
    assert.are.same({ "- ", "one" }, h.get_buf())
  end)

  it("removes an empty bullet instead of continuing it", function()
    h.set_buf({ "- one", "- " })
    h.set_cursor(2, 1)
    h.feed("a<CR>")
    h.ensure_normal()
    assert.are.same({ "- one", "" }, h.get_buf())
  end)
end)
