#!/usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

main() {
  [[ $# -eq 3 ]] || usage "Expected three arguments, got $#"
  
}

usage() {
  [[ $# -gt 0 ]] && echo "ERROR: $*"
  cat <<EOF
  USAGE: $(basename "$0") ARGUMENT

  Explanation

  Examples:

    $(basename "$0") foo
EOF
  exit 1
}

main "$@"

# cursor: 8 del
