#!/usr/bin/env bash

set -Eeuo pipefail
shopt -s inherit_errexit
trap 'echo "$0 failed at line $LINENO: $BASH_COMMAND"' ERR
# export SHELLOPTS  # This breaks any bash script you call.

main() {
  [[ $# -eq 3 ]] || usage "Expected three arguments, got $#"
  
}

usage() {
  [[ $# -gt 0 ]] && echo "ERROR: $*"
  local me=$(basename "$0")
  cat <<-EOF

  USAGE: $me ARGUMENT

  Explanation

  Examples:

    $me foo
	EOF
  exit 1
}

main "$@"

# cursor: 15 del
