#!/usr/bin/env bash

set -Eeuo pipefail
shopt -s inherit_errexit
trap 'echo "$0 failed at line $LINENO: $BASH_COMMAND"' ERR
[[ -v DEBUG ]] && set -x

main() {
  __has mods || usage "Must install mods first (https://github.com/charmbracelet/mods)"
  __has mdembed || usage "Must install mdembed first (https://github.com/croaky/mdembed)"
  [[ $# -ge 1 ]] || usage "Expected at least 1 argument, got $#"

  # Sed magic is to remove any shebang lines at the top of the file
  sed '1s/^#!.*$//' "$1" | mdembed | mods
}

__has() {
  command -v "$1" > /dev/null
}

usage() {
  [[ $# -gt 0 ]] && echo "  ERROR: $*"
  local me=$(basename "$0")
  cat <<-EOF

  USAGE: $me prompt.md

  Runs the prompt against Claude (via mods)

  Examples:

    $me blog_summary.md
	EOF
  exit 1
}

main "$@"

# cursor: 15 del
