#!/usr/bin/env bash

set -Eeuo pipefail
shopt -s inherit_errexit
trap 'echo "$0 failed at line $LINENO: $BASH_COMMAND"' ERR
[[ -v DEBUG ]] && set -x

cd "$(dirname "$0")"

export HOMEBREW_NO_AUTO_UPDATE=1
# https://github.com/Homebrew/homebrew-bundle/pull/552
export HOMEBREW_BUNDLE_NO_LOCK=true

brew update
brew bundle install --cleanup --force
brew list --versions > "installed-$(hostname -s).txt"

echo Updating gcloud components
gcloud --quiet components update
