#!/usr/bin/env bash

set -Eeuo pipefail
shopt -s inherit_errexit
trap 'echo "$0 failed at line $LINENO: $BASH_COMMAND"' ERR
[[ -v DEBUG ]] && set -x

cd "$(dirname "$0")"

# https://github.com/Homebrew/homebrew-bundle/pull/552
export HOMEBREW_BUNDLE_NO_LOCK=true
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_DOWNLOAD_CONCURRENCY=auto # https://brew.sh/2025/08/05/homebrew-4.6.0/

brew update
brew bundle install --upgrade  | grep -Ev '^Using '
brew bundle cleanup --force
brew bundle upgrade
brew list --versions > "installed-$(hostname -s).txt"
if ! git diff --quiet HEAD -- installed-*.txt; then
  git add installed-*.txt
  git commit -m "Automated: record new brew formula versions."
fi
