#!/usr/bin/env bash

set -Eeuo pipefail
shopt -s inherit_errexit
trap 'echo "$0 failed at line $LINENO: $BASH_COMMAND"' ERR
[[ -v DEBUG ]] && set -x

cd "$(dirname "$0")"

# https://github.com/Homebrew/homebrew-bundle/pull/552
export HOMEBREW_BUNDLE_NO_LOCK=true
export HOMEBREW_NO_AUTO_UPDATE=1

brew update
brew bundle install --upgrade --cleanup --force
brew list --versions > "installed-$(hostname -s).txt"
